# Generated by Django 4.1.5 on 2023-03-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usermanagement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='ps',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
