# Generated by Django 4.1 on 2022-09-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrNumber', models.CharField(max_length=10)),
                ('bookingDate', models.CharField(max_length=20)),
                ('bookingBranch', models.CharField(max_length=50)),
                ('deliveryBranch', models.CharField(max_length=50)),
                ('deliveryType', models.CharField(max_length=50)),
                ('consignore', models.CharField(max_length=50)),
                ('consignee', models.CharField(max_length=50)),
                ('billingAddress', models.CharField(max_length=100)),
                ('deliveryAddress', models.CharField(max_length=100)),
                ('vehicleNumber', models.CharField(max_length=10)),
                ('noa', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('billingType', models.CharField(max_length=20)),
                ('docNumber', models.CharField(default='', max_length=50)),
                ('docDate', models.CharField(default='', max_length=50)),
                ('packType', models.CharField(default='', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('invWeight', models.IntegerField(default=0)),
                ('remark', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
