# Generated by Django 4.1 on 2022-09-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingForm',
        ),
    ]
