# Generated by Django 4.1 on 2022-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
