# Generated by Django 4.1 on 2022-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookingform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50)),
                ('branchAddress', models.CharField(max_length=100)),
                ('branchCity', models.CharField(max_length=20)),
                ('branchState', models.CharField(max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('emailId', models.EmailField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
