# Generated by Django 4.1.1 on 2022-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_officelocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(default='Ready', max_length=10),
        ),
    ]
