# Generated by Django 4.1.1 on 2022-10-07 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bookingform_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=50)),
                ('branchAddress', models.CharField(max_length=100)),
                ('branchCity', models.CharField(max_length=20)),
                ('branchState', models.CharField(max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('emailId', models.EmailField(max_length=50)),
                ('ownerShip', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='OfficeLocations',
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 23, 13, 43, 558806)),
        ),
    ]
