# Generated by Django 4.1.1 on 2022-10-07 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_branchoffice_delete_officelocations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 7, 23, 13, 50, 417848)),
        ),
    ]
