# Generated by Django 4.1.1 on 2022-10-08 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_bookingform_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='loadType',
            field=models.CharField(default='FTL', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 12, 3, 51, 947097)),
        ),
    ]
