# Generated by Django 4.1.1 on 2022-10-08 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_bookingform_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='fgstn',
            field=models.CharField(default=29000000000, max_length=13),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='ngstn',
            field=models.CharField(default=29000000000, max_length=13),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 15, 35, 27, 825998)),
        ),
    ]
