# Generated by Django 4.1.1 on 2022-10-08 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_bookingform_fgstn_bookingform_ngstn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='freightAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 15, 39, 23, 649450)),
        ),
    ]
