# Generated by Django 4.1.1 on 2022-10-08 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_bookingform_freightamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='hamaliCharges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 16, 31, 17, 721138)),
        ),
    ]
