# Generated by Django 4.1.1 on 2022-10-08 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_bookingform_hamalicharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='mot',
            field=models.CharField(default='Road', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 17, 31, 47, 716533)),
        ),
    ]
