# Generated by Django 4.1.1 on 2022-10-10 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_bookingform_billingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 15, 14, 53, 984427), null=True),
        ),
    ]
