# Generated by Django 4.1.1 on 2022-10-16 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_bookingform_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='billingAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='billingType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 16, 10, 56, 5, 597567)),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='deliveryAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='docDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='docNumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='fgstn',
            field=models.CharField(default=29000000000, max_length=13),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='freightAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='hamaliCharges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='invWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='loadType',
            field=models.CharField(default='FTL', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='mot',
            field=models.CharField(blank=True, default='Road', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='ngstn',
            field=models.CharField(default=29000000000, max_length=13),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='noa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='packType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='remark',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(blank=True, default='Ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='vehicleNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
