# Generated by Django 4.1.1 on 2022-10-28 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_bookingform_billingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclenumber', models.CharField(max_length=10)),
                ('vehicletype', models.CharField(max_length=20)),
                ('capacityWeight', models.IntegerField(default=0, max_length=5)),
                ('loadWeight', models.IntegerField(default=0, max_length=5)),
                ('driverName', models.CharField(default='', max_length=20)),
                ('driverNumber', models.CharField(default='', max_length=12)),
                ('hireAmount', models.FloatField(default=0.0)),
                ('vendorName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 10, 28, 16, 36, 35, 238739)),
        ),
    ]
