# Generated by Django 4.0.5 on 2022-11-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_lorryhire_alter_bookingform_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryhire',
            name='tripNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 31, 3, 622223)),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='capacityWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lorryhire',
            name='loadWeight',
            field=models.IntegerField(default=0),
        ),
    ]
