# Generated by Django 4.0.5 on 2022-11-27 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_lorryhire_tripnumber_alter_bookingform_bookingdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingSheet',
            fields=[
                ('primery_key', models.CharField(auto_created='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=12, primary_key=True, serialize=False)),
                ('vehiclenumber', models.CharField(max_length=10)),
                ('weight', models.FloatField(default=0)),
                ('no_articals', models.IntegerField(default=0)),
                ('vendorName', models.CharField(max_length=50)),
                ('loadingBranch', models.CharField(max_length=50)),
                ('deliveryBranch', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lorryhire',
            name='tripDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 9, 7, 9, 481857)),
        ),
    ]
