# Generated by Django 4.0.5 on 2022-11-27 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_loadingsheet_lorryhire_tripdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingsheet',
            name='lrNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='loadingsheet',
            name='lsNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 9, 50, 42, 295025)),
        ),
    ]
