# Generated by Django 4.0.5 on 2022-11-29 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_loadingsheet_lrnumber_loadingsheet_lsnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='loadingSheet',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingform',
            name='pod_link',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 19, 24, 24, 99757)),
        ),
    ]
