# Generated by Django 4.0.5 on 2022-11-29 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_bookingform_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 19, 32, 21, 232363)),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='pod_link',
            field=models.FilePathField(default='', path='/pods'),
        ),
    ]
