# Generated by Django 4.0.5 on 2022-12-12 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_bookingform_bookingdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='producPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 8, 24, 57, 795663)),
        ),
    ]
